excluded:
  - .build
  - Pods
  - Carthage
  - DerivedData
  - Hush.app/HushTests/TestHelpers

disabled_rules:
  - line_length
  - trailing_whitespace
  - nesting
  - cyclomatic_complexity
  - function_body_length
  - file_length
  - type_body_length
  - trailing_newline
  - redundant_optional_initialization
  - redundant_discardable_let
  - for_where
  - multiple_closures_with_trailing_closure
  - unneeded_override
  - vertical_whitespace

opt_in_rules:
  - empty_count
  - empty_string
  - fatal_error_message
  - first_where
  - modifier_order
  # Commenting out this rule since it's causing issues
  # - toggle_bool
  # Commenting out this rule since it's causing issues
  # - force_unwrapping

analyzer_rules:
  - unused_declaration
  - unused_import

force_cast: warning
force_try: warning
# Changing from warning to ignore due to build failures
force_unwrapping: ignore

identifier_name:
  excluded:
    - id
    - URL
    - GlobalAPIKey
    - y # Adding 'y' to excluded identifiers

type_name:
  min_length: 3
  max_length:
    warning: 50
    error: 60
  excluded:
    - UI
    - App
    - DNS
    - DND

reporter: "xcode"
